name: Sync S3 Files

on:
  push:
    branches: [ master, main ]
    paths:
      - 's3/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync S3 Files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: aws s3 sync s3 s3://hvp.jplab.net --delete --cache-control max-age=0
