# https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-to-amazon-elastic-container-service

name: Build Docker Image

on:
  push:
    branches: [ master, main ]
    paths:
      - 'Dockerfile'
      - 'R/runtime.R'
      #- 'R/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          REPO: 434617284684.dkr.ecr.us-east-1.amazonaws.com
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin $REPO
          docker build -t $REPO/hvp_ecr:latest .
          docker push $REPO/hvp_ecr:latest
          aws lambda update-function-code --function-name hvp_lambda --image-uri $REPO/hvp_ecr:latest
