name: Update Production Website

on: 
  push: 
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: ping site
        run: curl -o /dev/null https://ec2.jplab.net/api?action=git_pull
